apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'leaderboard-dev'
spec:
  destination:
    name: 'in-cluster'
    namespace: 'dev'
  source:
    path: 'charts/leaderboard'
    repoURL: 'https://github.com/akuity/argo-cd-learning-assets.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-dev.yaml
  project: 'default'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
