name: Build

on:
  workflow_dispatch:
    inputs:
      container:
        description: 'The container to push'
        required: true
        default: 'akuity-devcontainer' 
        type: choice
        options:  # Folders under `containers/` that have a repo set up in Quay.
        - akuity-devcontainer
        - guestbook
        - leaderboard

run-name: Build ${{ inputs.container }}:${{ inputs.tag }}

jobs:
  push-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: 'containers/${{ inputs.container }}'
          push: false
          tags: quay.io/akuity/argo-cd-learning-assets/${{ inputs.container }}:pr-${{ github.event.pull_request.number }}
          platforms: 'linux/amd64,linux/arm64'