on:
  workflow_dispatch:
    inputs:
      container:
        description: 'The container to push'
        required: true
        default: 'leaderboard' 
        type: choice
        options:  # Folders under `containers/` that have a repo set up in Quay.
        - leaderboard 
      tag:
        description: 'The tag to push for the container.'
        required: true 
        type: string
jobs:
  push-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_AKUITY_LEARNING_CI_USERNAME }}
          password: ${{ secrets.QUAY_AKUITY_LEARNING_CI_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: 'containers/${{ inputs.container }}'
          file: ./Dockerfile
          push: true
          tags: quay.io/akuity/argo-cd-learning-assets/${{ inputs.container }}:${{ inputs.tag }}